- README.md
> [Misc] CAP Operator Lifecycle: Reuse compliant badge added

- .github/workflows/build.yml
- .github/workflows/docker-push.yml
- .github/workflows/publish-helm.yml
- Use owner env variable in workflow instead of hardcoded value
- disabled sonar for forks (conditional)
> [WORKFLOW] use owner to derive package/URL

- .github/workflows/build.yml
- .github/workflows/docker-push.yml
- .github/workflows/publish-helm.yml
- config/default/kustomization.yaml
CHANGES:
- the resulting packages are now `sap/cap-operator-lifecycle/helm/cap-operator:x.y.z` for the chart and `sap/cap-operator-lifecycle/cap-operator-manager:x.y.z` for the manager image
> [workflow] update package paths

- README.md
- Use coverage badge
- Link to overall summary
> [Misc] Readme: SonarCloud badge/link updated

- chart/README.md
Update to the latest state.
Change-Id: Ia4f8432a530b1f72c26ad57c867ef4f077e19d37
> [Misc] Chart: Readme updated

- internal/transformer/transformer.go
Removed dnsTarget length trimming
> [Fix] Removed dnsTarget length trimming

- chart/crds/sme.sap.com_capapplicationversions.yaml
Use the latest version of CAP Operator CRDs.
Change-Id: I6186545c789581b28891bff2e1e9ba5f88e487b6
> [Misc] chart: CAP Operator crds updated

- chart/Chart.yaml
- chart/README.md
> [Misc] Chart: Bump up version before release

- Dockerfile
- go.mod
- go.sum
- Use latest version of Go
- Use latest version of Go dependencies
> [Misc] Operator: Go Dependencies updated

- chart/Chart.yaml
- chart/README.md
- chart/templates/server-rbac.yaml
Update RBAC to match current state
> [Misc] Chart: RBAC update for subscriptionContext

- chart/Chart.yaml
- chart/README.md
- chart/templates/controller-deployment.yaml
Point to the upcoming release version(s).
Related to: https://github.com/SAP/cap-operator/pull/104
> [Misc] helm: Chart version updated

- chart/Chart.yaml
- chart/README.md
- chart/crds/sme.sap.com_capapplications.yaml
- chart/crds/sme.sap.com_capapplicationversions.yaml
- chart/crds/sme.sap.com_captenantoperations.yaml
- chart/crds/sme.sap.com_captenantoutputs.yaml
- chart/crds/sme.sap.com_captenants.yaml
- chart/templates/controller-rbac.yaml
- chart/templates/server-rbac.yaml
- chart/templates/webhook-rbac.yaml
Update CRDs, rbac to add support for CAPTenantOutput resource.
> [Misc] Chart: Support for CAPTenantOutput added

- chart/Chart.yaml
- chart/README.md
- chart/crds/sme.sap.com_capapplications.yaml
- chart/crds/sme.sap.com_capapplicationversions.yaml
- chart/crds/sme.sap.com_captenantoperations.yaml
- chart/crds/sme.sap.com_captenantoutputs.yaml
- chart/crds/sme.sap.com_captenants.yaml
Updates before the next release.
> [Misc] Chart: Version and CRDs updated

- CONTRIBUTING.md
Reference to guideline for AI-generated code contributions to SAP Open Source Software Projects
> [README] AI-generated code guideline referenced

- go.mod
- go.sum
Update to the latest version of Go dependencies.
> [Misc] OperatorManager: Dependencies updated

- chart/Chart.yaml
- chart/README.md
- chart/crds/sme.sap.com_capapplicationversions.yaml
- chart/templates/controller-deployment.yaml
- chart/templates/controller-rbac.yaml
- chart/templates/server-deployment.yaml
- chart/values.yaml
CHANGES:
- CRD `capapplicationversions` enhanced with `monitoring.scrapeConfig` and `monitoring.deletionRules`
- Controller RBAC enhanced to access CRD's and ServiceMonitors
- Controller deployment enhanced with version monitoring environment variables
> [FEAT] chart enhancements for version monitoring

- chart/Chart.yaml
- chart/README.md
Bump up versions before release.
> [Release] helm: 0.10.0 version release

- chart/Chart.yaml
- chart/README.md
Update version(s) prior to release of `0.14.1`
> [Pre-Release] Chart version(s) updated

- chart/templates/cluster-role.yaml
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles
> [Misc] CAP Operator aggregated ClusterRoles

- chart/Chart.yaml
- chart/README.md
- chart/crds/sme.sap.com_clusterdomains.yaml
- chart/crds/sme.sap.com_domains.yaml
> [Release] helm: chart updated

- chart/crds/sme.sap.com_capapplications.yaml
- chart/crds/sme.sap.com_capapplicationversions.yaml
- chart/crds/sme.sap.com_captenantoperations.yaml
- chart/crds/sme.sap.com_captenantoutputs.yaml
- chart/crds/sme.sap.com_captenants.yaml
- chart/crds/sme.sap.com_clusterdomains.yaml
- chart/crds/sme.sap.com_domains.yaml
Update to the latest version of CRDs
> [Misc] Chart: CRDs updated
